# Makefile.in generated by automake 1.11.1 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002,
# 2003, 2004, 2005, 2006, 2007, 2008, 2009  Free Software Foundation,
# Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.





pkgdatadir = $(datadir)/BitSmear
pkgincludedir = $(includedir)/BitSmear
pkglibdir = $(libdir)/BitSmear
pkglibexecdir = $(libexecdir)/BitSmear
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_triplet = x86_64-apple-darwin11.2.0
host_triplet = x86_64-apple-darwin11.2.0
bin_PROGRAMS = miniDHT_server$(EXEEXT) miniDHT_test$(EXEEXT) \
	miniDHT_send$(EXEEXT) miniDHT_recv$(EXEEXT) $(am__EXEEXT_1) \
	$(am__EXEEXT_2)
am__append_1 = BitSmear
am__append_2 = BitSmear.app
subdir = .
DIST_COMMON = README $(am__configure_deps) $(srcdir)/Makefile.am \
	$(srcdir)/Makefile.in $(srcdir)/config.h.in \
	$(top_srcdir)/configure AUTHORS COPYING ChangeLog INSTALL NEWS \
	TODO config.guess config.sub depcomp install-sh ltmain.sh \
	missing
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/m4/libtool.m4 \
	$(top_srcdir)/m4/ltoptions.m4 $(top_srcdir)/m4/ltsugar.m4 \
	$(top_srcdir)/m4/ltversion.m4 $(top_srcdir)/m4/lt~obsolete.m4 \
	$(top_srcdir)/m4/ax_boost_base.m4 \
	$(top_srcdir)/m4/ax_lib_sqlite3.m4 \
	$(top_srcdir)/m4/ax_boost_asio.m4 \
	$(top_srcdir)/m4/ax_boost_date_time.m4 \
	$(top_srcdir)/m4/ax_boost_filesystem.m4 \
	$(top_srcdir)/m4/ax_boost_program_options.m4 \
	$(top_srcdir)/m4/ax_boost_serialization.m4 \
	$(top_srcdir)/m4/ax_boost_system.m4 \
	$(top_srcdir)/m4/ax_boost_thread.m4 \
	$(top_srcdir)/m4/ax_check_openssl.m4 \
	$(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno config.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_HEADER = config.h
CONFIG_CLEAN_FILES =
CONFIG_CLEAN_VPATH_FILES =
am__vpath_adj_setup = srcdirstrip=`echo "$(srcdir)" | sed 's|.|.|g'`;
am__vpath_adj = case $$p in \
    $(srcdir)/*) f=`echo "$$p" | sed "s|^$$srcdirstrip/||"`;; \
    *) f=$$p;; \
  esac;
am__strip_dir = f=`echo $$p | sed -e 's|^.*/||'`;
am__install_max = 40
am__nobase_strip_setup = \
  srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*|]/\\\\&/g'`
am__nobase_strip = \
  for p in $$list; do echo "$$p"; done | sed -e "s|$$srcdirstrip/||"
am__nobase_list = $(am__nobase_strip_setup); \
  for p in $$list; do echo "$$p $$p"; done | \
  sed "s| $$srcdirstrip/| |;"' / .*\//!s/ .*/ ./; s,\( .*\)/[^/]*$$,\1,' | \
  $(AWK) 'BEGIN { files["."] = "" } { files[$$2] = files[$$2] " " $$1; \
    if (++n[$$2] == $(am__install_max)) \
      { print $$2, files[$$2]; n[$$2] = 0; files[$$2] = "" } } \
    END { for (dir in files) print dir, files[dir] }'
am__base_list = \
  sed '$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;s/\n/ /g' | \
  sed '$$!N;$$!N;$$!N;$$!N;s/\n/ /g'
am__installdirs = "$(DESTDIR)$(libdir)" "$(DESTDIR)$(bindir)"
LTLIBRARIES = $(lib_LTLIBRARIES)
libminiDHT_1_0_la_LIBADD =
am_libminiDHT_1_0_la_OBJECTS = miniDHT.lo miniDHT_db.lo \
	miniDHT_const.lo
nodist_libminiDHT_1_0_la_OBJECTS = miniDHT_proto.pb.lo
libminiDHT_1_0_la_OBJECTS = $(am_libminiDHT_1_0_la_OBJECTS) \
	$(nodist_libminiDHT_1_0_la_OBJECTS)
am__EXEEXT_1 = BitSmear$(EXEEXT)
am__EXEEXT_2 = BitSmear.app$(EXEEXT)
PROGRAMS = $(bin_PROGRAMS)
am__BitSmear_SOURCES_DIST = gui_main.cpp gui_main.h \
	gui_network_status.h gui_network_status.cpp gui_info.h \
	gui_info.cpp gui_frame.h gui_frame.cpp gui_connect.h \
	gui_connect.cpp gui_dht.h gui_dht.cpp gui_list_ctrl.h \
	gui_list_ctrl.cpp send.h send.cpp recv.h recv.cpp miniDHT.h
am_BitSmear_OBJECTS = gui_main.$(OBJEXT) \
	gui_network_status.$(OBJEXT) gui_info.$(OBJEXT) \
	gui_frame.$(OBJEXT) gui_connect.$(OBJEXT) \
	gui_dht.$(OBJEXT) gui_list_ctrl.$(OBJEXT) \
	send.$(OBJEXT) recv.$(OBJEXT)
BitSmear_OBJECTS = $(am_BitSmear_OBJECTS)
BitSmear_DEPENDENCIES = libminiDHT-1.0.la
BitSmear_LINK = $(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CXXLD) $(AM_CXXFLAGS) \
	$(CXXFLAGS) $(BitSmear_LDFLAGS) $(LDFLAGS) -o $@
BitSmear_app_SOURCES = BitSmear.c
BitSmear_app_OBJECTS = BitSmear.$(OBJEXT)
BitSmear_app_LDADD = $(LDADD)
am_miniDHT_recv_OBJECTS = miniDHT_recv-recv.$(OBJEXT)
miniDHT_recv_OBJECTS = $(am_miniDHT_recv_OBJECTS)
miniDHT_recv_DEPENDENCIES = libminiDHT-1.0.la
miniDHT_recv_LINK = $(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CXXLD) $(AM_CXXFLAGS) \
	$(CXXFLAGS) $(miniDHT_recv_LDFLAGS) $(LDFLAGS) -o $@
am_miniDHT_send_OBJECTS = miniDHT_send-send.$(OBJEXT)
miniDHT_send_OBJECTS = $(am_miniDHT_send_OBJECTS)
miniDHT_send_DEPENDENCIES = libminiDHT-1.0.la
miniDHT_send_LINK = $(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CXXLD) $(AM_CXXFLAGS) \
	$(CXXFLAGS) $(miniDHT_send_LDFLAGS) $(LDFLAGS) -o $@
am_miniDHT_server_OBJECTS = server.$(OBJEXT)
miniDHT_server_OBJECTS = $(am_miniDHT_server_OBJECTS)
miniDHT_server_DEPENDENCIES = libminiDHT-1.0.la
miniDHT_server_LINK = $(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CXXLD) $(AM_CXXFLAGS) \
	$(CXXFLAGS) $(miniDHT_server_LDFLAGS) $(LDFLAGS) -o $@
am_miniDHT_test_OBJECTS = test.$(OBJEXT)
miniDHT_test_OBJECTS = $(am_miniDHT_test_OBJECTS)
miniDHT_test_DEPENDENCIES = libminiDHT-1.0.la
miniDHT_test_LINK = $(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CXXLD) $(AM_CXXFLAGS) \
	$(CXXFLAGS) $(miniDHT_test_LDFLAGS) $(LDFLAGS) -o $@
DEFAULT_INCLUDES = -I.
depcomp = $(SHELL) $(top_srcdir)/depcomp
am__depfiles_maybe = depfiles
am__mv = mv -f
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
LTCOMPILE = $(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) \
	--mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
CCLD = $(CC)
LINK = $(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) \
	--mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(AM_LDFLAGS) \
	$(LDFLAGS) -o $@
CXXCOMPILE = $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
LTCXXCOMPILE = $(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) \
	--mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
CXXLD = $(CXX)
CXXLINK = $(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) \
	--mode=link $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_LDFLAGS) \
	$(LDFLAGS) -o $@
SOURCES = $(libminiDHT_1_0_la_SOURCES) \
	$(nodist_libminiDHT_1_0_la_SOURCES) $(BitSmear_SOURCES) \
	BitSmear.c $(miniDHT_recv_SOURCES) $(miniDHT_send_SOURCES) \
	$(miniDHT_server_SOURCES) $(miniDHT_test_SOURCES)
DIST_SOURCES = $(libminiDHT_1_0_la_SOURCES) \
	$(am__BitSmear_SOURCES_DIST) BitSmear.c \
	$(miniDHT_recv_SOURCES) $(miniDHT_send_SOURCES) \
	$(miniDHT_server_SOURCES) $(miniDHT_test_SOURCES)
ETAGS = etags
CTAGS = ctags
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  { test ! -d "$(distdir)" \
    || { find "$(distdir)" -type d ! -perm -200 -exec chmod u+w {} ';' \
         && rm -fr "$(distdir)"; }; }
DIST_ARCHIVES = $(distdir).tar.gz
GZIP_ENV = --best
distuninstallcheck_listfiles = find . -type f -print
distcleancheck_listfiles = find . -type f -print
ACLOCAL = ${SHELL} /Users/mic/Dropbox/miniDHT/missing --run aclocal-1.11
AMTAR = ${SHELL} /Users/mic/Dropbox/miniDHT/missing --run tar
AR = ar
AUTOCONF = ${SHELL} /Users/mic/Dropbox/miniDHT/missing --run autoconf
AUTOHEADER = ${SHELL} /Users/mic/Dropbox/miniDHT/missing --run autoheader
AUTOMAKE = ${SHELL} /Users/mic/Dropbox/miniDHT/missing --run automake-1.11
AWK = awk
BOOST_ASIO_LIB = -lboost_system
BOOST_CPPFLAGS = -pthread -I/opt/local/include
BOOST_DATE_TIME_LIB = -lboost_date_time-mt
BOOST_FILESYSTEM_LIB = -lboost_filesystem-mt
BOOST_LDFLAGS = -L/opt/local/lib
BOOST_LIB_DIR = /opt/local/lib
BOOST_PROGRAM_OPTIONS_LIB = -lboost_program_options-mt
BOOST_SYSTEM_LIB = -lboost_system-mt
BOOST_THREAD_LIB = -lboost_thread-mt
CC = clang
CCDEPMODE = depmode=gcc3
CFLAGS = -g -O2 
CPP = clang -E
CPPFLAGS =  -I/usr/include -I/opt/local/include   -pthread -I/opt/local/include -I/opt/local/lib/wx/include/osx_cocoa-unicode-2.9 -I/opt/local/include/wx-2.9 -D_FILE_OFFSET_BITS=64 -DWXUSINGDLL -D__WXMAC__ -D__WXOSX__ -D__WXOSX_COCOA__ -D_THREAD_SAFE -I/opt/local/include  
CXX = clang++
CXXCPP = clang++ -E
CXXDEPMODE = depmode=gcc3
CXXFLAGS = -g -O2 -I/opt/local/lib/wx/include/osx_cocoa-unicode-2.9 -I/opt/local/include/wx-2.9 -D_FILE_OFFSET_BITS=64 -DWXUSINGDLL -D__WXMAC__ -D__WXOSX__ -D__WXOSX_COCOA__
CYGPATH_W = echo
DEFS = -DHAVE_CONFIG_H
DEPDIR = .deps
DLLTOOL = false
DSYMUTIL = dsymutil
DUMPBIN = 
ECHO_C = \c
ECHO_N = 
ECHO_T = 
EGREP = /usr/bin/grep -E
EXEEXT = 
FGREP = /usr/bin/grep -F
GREP = /usr/bin/grep
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
LD = /usr/bin/ld
LDFLAGS = 
LIBOBJS =  ${LIBOBJDIR}error$U.o
LIBS =  -L/usr/lib -lsqlite3 -L/opt/local/lib   -lssl -lcrypto -lz   -L/opt/local/lib -lboost_system -lboost_date_time-mt -lboost_filesystem-mt -lboost_program_options-mt -lboost_system-mt -lboost_thread-mt -L/opt/local/lib   -framework IOKit -framework Carbon -framework Cocoa -framework AudioToolbox -framework System -framework OpenGL -framework QuickTime -lwx_osx_cocoau_xrc-2.9 -lwx_osx_cocoau_html-2.9 -lwx_osx_cocoau_qa-2.9 -lwx_osx_cocoau_adv-2.9 -lwx_osx_cocoau_core-2.9 -lwx_baseu_xml-2.9 -lwx_baseu_net-2.9 -lwx_baseu-2.9  -D_THREAD_SAFE -L/opt/local/lib -lprotobuf -lz  
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LIBTOOL_DEPS = ./ltmain.sh
LIPO = lipo
LN_S = ln -s
LTLIBOBJS =  ${LIBOBJDIR}error$U.lo
MAKEINFO = ${SHELL} /Users/mic/Dropbox/miniDHT/missing --run makeinfo
MANIFEST_TOOL = :
MKDIR_P = ./install-sh -c -d
NM = /usr/bin/nm
NMEDIT = nmedit
OBJDUMP = false
OBJEXT = o
OPENSSL_INCLUDES = -I/opt/local/include  
OPENSSL_LDFLAGS = -L/opt/local/lib  
OPENSSL_LIBS = -lssl -lcrypto -lz  
OTOOL = otool
OTOOL64 = :
PACKAGE = BitSmear
PACKAGE_BUGREPORT = frederic.dubouchet@gmail.com
PACKAGE_NAME = BitSmear
PACKAGE_STRING = BitSmear 1.0
PACKAGE_TARNAME = bitsmear
PACKAGE_URL = 
PACKAGE_VERSION = 1.0
PATH_SEPARATOR = :
PKG_CONFIG = /opt/local/bin/pkg-config
PKG_CONFIG_LIBDIR = 
PKG_CONFIG_PATH = 
PORT_LIB_DIR = /opt/local/lib
PROTOC = protoc
RANLIB = ranlib
SED = /usr/bin/sed
SET_MAKE = 
SHELL = /bin/sh
SQLITE3_CFLAGS = -I/usr/include
SQLITE3_LDFLAGS = -L/usr/lib -lsqlite3
SQLITE3_VERSION = 3.7.5
STRIP = strip
VERSION = 1.0
WX_CFLAGS = -I/opt/local/lib/wx/include/osx_cocoa-unicode-2.9 -I/opt/local/include/wx-2.9 -D_FILE_OFFSET_BITS=64 -DWXUSINGDLL -D__WXMAC__ -D__WXOSX__ -D__WXOSX_COCOA__ 
WX_CFLAGS_ONLY = 
WX_CONFIG_PATH = /opt/local/bin/wx-config
WX_CPPFLAGS = -I/opt/local/lib/wx/include/osx_cocoa-unicode-2.9 -I/opt/local/include/wx-2.9 -D_FILE_OFFSET_BITS=64 -DWXUSINGDLL -D__WXMAC__ -D__WXOSX__ -D__WXOSX_COCOA__
WX_CXXFLAGS = -I/opt/local/lib/wx/include/osx_cocoa-unicode-2.9 -I/opt/local/include/wx-2.9 -D_FILE_OFFSET_BITS=64 -DWXUSINGDLL -D__WXMAC__ -D__WXOSX__ -D__WXOSX_COCOA__ 
WX_CXXFLAGS_ONLY = -I/opt/local/lib/wx/include/osx_cocoa-unicode-2.9 -I/opt/local/include/wx-2.9 -D_FILE_OFFSET_BITS=64 -DWXUSINGDLL -D__WXMAC__ -D__WXOSX__ -D__WXOSX_COCOA__
WX_LIBS = -L/opt/local/lib   -framework IOKit -framework Carbon -framework Cocoa -framework AudioToolbox -framework System -framework OpenGL -framework QuickTime -lwx_osx_cocoau_xrc-2.9 -lwx_osx_cocoau_html-2.9 -lwx_osx_cocoau_qa-2.9 -lwx_osx_cocoau_adv-2.9 -lwx_osx_cocoau_core-2.9 -lwx_baseu_xml-2.9 -lwx_baseu_net-2.9 -lwx_baseu-2.9 
WX_LIBS_STATIC = 
WX_RESCOMP = cat /dev/null | Rez -d __DARWIN__ -t APPL /opt/local/lib/libwx_osx_cocoau-2.9.2.r
WX_VERSION = 2.9.2
WX_VERSION_MAJOR = 2
WX_VERSION_MICRO = 2
WX_VERSION_MINOR = 9
abs_builddir = /Users/mic/Dropbox/miniDHT
abs_srcdir = /Users/mic/Dropbox/miniDHT
abs_top_builddir = /Users/mic/Dropbox/miniDHT
abs_top_srcdir = /Users/mic/Dropbox/miniDHT
ac_ct_AR = ar
ac_ct_CC = clang
ac_ct_CXX = clang++
ac_ct_DUMPBIN = 
am__include = include
am__leading_dot = .
am__quote = 
am__tar = ${AMTAR} chof - "$$tardir"
am__untar = ${AMTAR} xf -
bindir = ${exec_prefix}/bin
build = x86_64-apple-darwin11.2.0
build_alias = 
build_cpu = x86_64
build_os = darwin11.2.0
build_vendor = apple
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
host = x86_64-apple-darwin11.2.0
host_alias = 
host_cpu = x86_64
host_os = darwin11.2.0
host_vendor = apple
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /Users/mic/Dropbox/miniDHT/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = $(top_builddir)/./install-sh -c -d
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /usr/local
program_transform_name = s,x,x,
protobuf_CFLAGS = -D_THREAD_SAFE -I/opt/local/include  
protobuf_LIBS = -D_THREAD_SAFE -L/opt/local/lib -lprotobuf -lz  
psdir = ${docdir}
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target_alias = 
top_build_prefix = 
top_builddir = .
top_srcdir = .
ACLOCAL_AMFLAGS = -I m4
AM_CPPFLAGS = -arch x86_64 -arch i386 -mmacosx-version-min=10.6  
AM_LDFLAGS = -arch x86_64 -arch i386 -mmacosx-version-min=10.6 -headerpad_max_install_names
miniDHT_server_SOURCES = server.cpp miniDHT.h
miniDHT_server_LDADD = libminiDHT-1.0.la
miniDHT_server_LDFLAGS = $(AM_LDFLAGS) -static libminiDHT-1.0.la
miniDHT_test_SOURCES = test.cpp miniDHT.h libminiDHT-1.0.la
miniDHT_test_LDADD = libminiDHT-1.0.la
miniDHT_test_LDFLAGS = $(AM_LDFLAGS) -static libminiDHT-1.0.la
miniDHT_send_CPPFLAGS = -DSEND_MAIN_TEST $(AM_CPPFLAGS)
miniDHT_send_SOURCES = send.cpp send.h miniDHT.h libminiDHT-1.0.la
miniDHT_send_LDADD = libminiDHT-1.0.la
miniDHT_send_LDFLAGS = $(AM_LDFLAGS) -static libminiDHT-1.0.la
miniDHT_recv_CPPFLAGS = -DRECV_MAIN_TEST $(AM_CPPFLAGS)
miniDHT_recv_SOURCES = recv.cpp recv.h miniDHT.h libminiDHT-1.0.la
miniDHT_recv_LDADD = libminiDHT-1.0.la
miniDHT_recv_LDFLAGS = $(AM_LDFLAGS) -static libminiDHT-1.0.la
BitSmear_SOURCES = gui_main.cpp gui_main.h gui_network_status.h gui_network_status.cpp gui_info.h gui_info.cpp gui_frame.h gui_frame.cpp gui_connect.h gui_connect.cpp gui_dht.h gui_dht.cpp gui_list_ctrl.h gui_list_ctrl.cpp send.h send.cpp recv.h recv.cpp miniDHT.h
BitSmear_LDFLAGS = $(AM_LDFLAGS) -static libminiDHT-1.0.la
BitSmear_LDADD = libminiDHT-1.0.la
lib_LTLIBRARIES = libminiDHT-1.0.la
libminiDHT_1_0_la_SOURCES = miniDHT.cpp miniDHT.h miniDHT_db.cpp miniDHT_db.h miniDHT_const.cpp miniDHT_const.h miniDHT_bucket.h miniDHT_search.h miniDHT_session.h  
nodist_libminiDHT_1_0_la_SOURCES = miniDHT_proto.pb.h miniDHT_proto.pb.cc
BUILT_SOURCES = miniDHT_proto.pb.h miniDHT_proto.pb.cc
CLEANFILES = miniDHT_proto.pb.h miniDHT_proto.pb.cc
all: $(BUILT_SOURCES) config.h
	$(MAKE) $(AM_MAKEFLAGS) all-am

.SUFFIXES:
.SUFFIXES: .c .cc .cpp .lo .o .obj
am--refresh:
	@:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --gnu'; \
	      $(am__cd) $(srcdir) && $(AUTOMAKE) --gnu \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --gnu Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --gnu Makefile
.PRECIOUS: Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure:  $(am__configure_deps)
	$(am__cd) $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	$(am__cd) $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)
$(am__aclocal_m4_deps):

config.h: stamp-h1
	@if test ! -f $@; then \
	  rm -f stamp-h1; \
	  $(MAKE) $(AM_MAKEFLAGS) stamp-h1; \
	else :; fi

stamp-h1: $(srcdir)/config.h.in $(top_builddir)/config.status
	@rm -f stamp-h1
	cd $(top_builddir) && $(SHELL) ./config.status config.h
$(srcdir)/config.h.in:  $(am__configure_deps) 
	($(am__cd) $(top_srcdir) && $(AUTOHEADER))
	rm -f stamp-h1
	touch $@

distclean-hdr:
	-rm -f config.h stamp-h1
install-libLTLIBRARIES: $(lib_LTLIBRARIES)
	@$(NORMAL_INSTALL)
	test -z "$(libdir)" || $(MKDIR_P) "$(DESTDIR)$(libdir)"
	@list='$(lib_LTLIBRARIES)'; test -n "$(libdir)" || list=; \
	list2=; for p in $$list; do \
	  if test -f $$p; then \
	    list2="$$list2 $$p"; \
	  else :; fi; \
	done; \
	test -z "$$list2" || { \
	  echo " $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL) $(INSTALL_STRIP_FLAG) $$list2 '$(DESTDIR)$(libdir)'"; \
	  $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL) $(INSTALL_STRIP_FLAG) $$list2 "$(DESTDIR)$(libdir)"; \
	}

uninstall-libLTLIBRARIES:
	@$(NORMAL_UNINSTALL)
	@list='$(lib_LTLIBRARIES)'; test -n "$(libdir)" || list=; \
	for p in $$list; do \
	  $(am__strip_dir) \
	  echo " $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=uninstall rm -f '$(DESTDIR)$(libdir)/$$f'"; \
	  $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=uninstall rm -f "$(DESTDIR)$(libdir)/$$f"; \
	done

clean-libLTLIBRARIES:
	-test -z "$(lib_LTLIBRARIES)" || rm -f $(lib_LTLIBRARIES)
	@list='$(lib_LTLIBRARIES)'; for p in $$list; do \
	  dir="`echo $$p | sed -e 's|/[^/]*$$||'`"; \
	  test "$$dir" != "$$p" || dir=.; \
	  echo "rm -f \"$${dir}/so_locations\""; \
	  rm -f "$${dir}/so_locations"; \
	done
libminiDHT-1.0.la: $(libminiDHT_1_0_la_OBJECTS) $(libminiDHT_1_0_la_DEPENDENCIES) 
	$(CXXLINK) -rpath $(libdir) $(libminiDHT_1_0_la_OBJECTS) $(libminiDHT_1_0_la_LIBADD) $(LIBS)
install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	test -z "$(bindir)" || $(MKDIR_P) "$(DESTDIR)$(bindir)"
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	for p in $$list; do echo "$$p $$p"; done | \
	sed 's/$(EXEEXT)$$//' | \
	while read p p1; do if test -f $$p || test -f $$p1; \
	  then echo "$$p"; echo "$$p"; else :; fi; \
	done | \
	sed -e 'p;s,.*/,,;n;h' -e 's|.*|.|' \
	    -e 'p;x;s,.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/' | \
	sed 'N;N;N;s,\n, ,g' | \
	$(AWK) 'BEGIN { files["."] = ""; dirs["."] = 1 } \
	  { d=$$3; if (dirs[d] != 1) { print "d", d; dirs[d] = 1 } \
	    if ($$2 == $$4) files[d] = files[d] " " $$1; \
	    else { print "f", $$3 "/" $$4, $$1; } } \
	  END { for (d in files) print "f", d, files[d] }' | \
	while read type dir files; do \
	    if test "$$dir" = .; then dir=; else dir=/$$dir; fi; \
	    test -z "$$files" || { \
	    echo " $(INSTALL_PROGRAM_ENV) $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL_PROGRAM) $$files '$(DESTDIR)$(bindir)$$dir'"; \
	    $(INSTALL_PROGRAM_ENV) $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL_PROGRAM) $$files "$(DESTDIR)$(bindir)$$dir" || exit $$?; \
	    } \
	; done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	files=`for p in $$list; do echo "$$p"; done | \
	  sed -e 'h;s,^.*/,,;s/$(EXEEXT)$$//;$(transform)' \
	      -e 's/$$/$(EXEEXT)/' `; \
	test -n "$$list" || exit 0; \
	echo " ( cd '$(DESTDIR)$(bindir)' && rm -f" $$files ")"; \
	cd "$(DESTDIR)$(bindir)" && rm -f $$files

clean-binPROGRAMS:
	@list='$(bin_PROGRAMS)'; test -n "$$list" || exit 0; \
	echo " rm -f" $$list; \
	rm -f $$list || exit $$?; \
	test -n "$(EXEEXT)" || exit 0; \
	list=`for p in $$list; do echo "$$p"; done | sed 's/$(EXEEXT)$$//'`; \
	echo " rm -f" $$list; \
	rm -f $$list
BitSmear$(EXEEXT): $(BitSmear_OBJECTS) $(BitSmear_DEPENDENCIES) 
	@rm -f BitSmear$(EXEEXT)
	$(BitSmear_LINK) $(BitSmear_OBJECTS) $(BitSmear_LDADD) $(LIBS)
#BitSmear.app$(EXEEXT): $(BitSmear_app_OBJECTS) $(BitSmear_app_DEPENDENCIES) 
#	@rm -f BitSmear.app$(EXEEXT)
#	$(LINK) $(BitSmear_app_OBJECTS) $(BitSmear_app_LDADD) $(LIBS)
miniDHT_recv$(EXEEXT): $(miniDHT_recv_OBJECTS) $(miniDHT_recv_DEPENDENCIES) 
	@rm -f miniDHT_recv$(EXEEXT)
	$(miniDHT_recv_LINK) $(miniDHT_recv_OBJECTS) $(miniDHT_recv_LDADD) $(LIBS)
miniDHT_send$(EXEEXT): $(miniDHT_send_OBJECTS) $(miniDHT_send_DEPENDENCIES) 
	@rm -f miniDHT_send$(EXEEXT)
	$(miniDHT_send_LINK) $(miniDHT_send_OBJECTS) $(miniDHT_send_LDADD) $(LIBS)
miniDHT_server$(EXEEXT): $(miniDHT_server_OBJECTS) $(miniDHT_server_DEPENDENCIES) 
	@rm -f miniDHT_server$(EXEEXT)
	$(miniDHT_server_LINK) $(miniDHT_server_OBJECTS) $(miniDHT_server_LDADD) $(LIBS)
miniDHT_test$(EXEEXT): $(miniDHT_test_OBJECTS) $(miniDHT_test_DEPENDENCIES) 
	@rm -f miniDHT_test$(EXEEXT)
	$(miniDHT_test_LINK) $(miniDHT_test_OBJECTS) $(miniDHT_test_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

include ./$(DEPDIR)/BitSmear.Po
include ./$(DEPDIR)/gui_connect.Po
include ./$(DEPDIR)/gui_dht.Po
include ./$(DEPDIR)/gui_frame.Po
include ./$(DEPDIR)/gui_info.Po
include ./$(DEPDIR)/gui_list_ctrl.Po
include ./$(DEPDIR)/gui_main.Po
include ./$(DEPDIR)/gui_network_status.Po
include ./$(DEPDIR)/miniDHT.Plo
include ./$(DEPDIR)/miniDHT_const.Plo
include ./$(DEPDIR)/miniDHT_db.Plo
include ./$(DEPDIR)/miniDHT_proto.pb.Plo
include ./$(DEPDIR)/miniDHT_recv-recv.Po
include ./$(DEPDIR)/miniDHT_send-send.Po
include ./$(DEPDIR)/recv.Po
include ./$(DEPDIR)/send.Po
include ./$(DEPDIR)/server.Po
include ./$(DEPDIR)/test.Po

.c.o:
	$(COMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ $<
	$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(COMPILE) -c $<

.c.obj:
	$(COMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ `$(CYGPATH_W) '$<'`
	$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(COMPILE) -c `$(CYGPATH_W) '$<'`

.c.lo:
	$(LTCOMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ $<
	$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Plo
#	source='$<' object='$@' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LTCOMPILE) -c -o $@ $<

.cc.o:
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ $<
	$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXXCOMPILE) -c -o $@ $<

.cc.obj:
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ `$(CYGPATH_W) '$<'`
	$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXXCOMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

.cc.lo:
	$(LTCXXCOMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ $<
	$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Plo
#	source='$<' object='$@' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LTCXXCOMPILE) -c -o $@ $<

miniDHT_recv-recv.o: recv.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(miniDHT_recv_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT miniDHT_recv-recv.o -MD -MP -MF $(DEPDIR)/miniDHT_recv-recv.Tpo -c -o miniDHT_recv-recv.o `test -f 'recv.cpp' || echo '$(srcdir)/'`recv.cpp
	$(am__mv) $(DEPDIR)/miniDHT_recv-recv.Tpo $(DEPDIR)/miniDHT_recv-recv.Po
#	source='recv.cpp' object='miniDHT_recv-recv.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(miniDHT_recv_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o miniDHT_recv-recv.o `test -f 'recv.cpp' || echo '$(srcdir)/'`recv.cpp

miniDHT_recv-recv.obj: recv.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(miniDHT_recv_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT miniDHT_recv-recv.obj -MD -MP -MF $(DEPDIR)/miniDHT_recv-recv.Tpo -c -o miniDHT_recv-recv.obj `if test -f 'recv.cpp'; then $(CYGPATH_W) 'recv.cpp'; else $(CYGPATH_W) '$(srcdir)/recv.cpp'; fi`
	$(am__mv) $(DEPDIR)/miniDHT_recv-recv.Tpo $(DEPDIR)/miniDHT_recv-recv.Po
#	source='recv.cpp' object='miniDHT_recv-recv.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(miniDHT_recv_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o miniDHT_recv-recv.obj `if test -f 'recv.cpp'; then $(CYGPATH_W) 'recv.cpp'; else $(CYGPATH_W) '$(srcdir)/recv.cpp'; fi`

miniDHT_send-send.o: send.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(miniDHT_send_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT miniDHT_send-send.o -MD -MP -MF $(DEPDIR)/miniDHT_send-send.Tpo -c -o miniDHT_send-send.o `test -f 'send.cpp' || echo '$(srcdir)/'`send.cpp
	$(am__mv) $(DEPDIR)/miniDHT_send-send.Tpo $(DEPDIR)/miniDHT_send-send.Po
#	source='send.cpp' object='miniDHT_send-send.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(miniDHT_send_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o miniDHT_send-send.o `test -f 'send.cpp' || echo '$(srcdir)/'`send.cpp

miniDHT_send-send.obj: send.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(miniDHT_send_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT miniDHT_send-send.obj -MD -MP -MF $(DEPDIR)/miniDHT_send-send.Tpo -c -o miniDHT_send-send.obj `if test -f 'send.cpp'; then $(CYGPATH_W) 'send.cpp'; else $(CYGPATH_W) '$(srcdir)/send.cpp'; fi`
	$(am__mv) $(DEPDIR)/miniDHT_send-send.Tpo $(DEPDIR)/miniDHT_send-send.Po
#	source='send.cpp' object='miniDHT_send-send.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(miniDHT_send_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o miniDHT_send-send.obj `if test -f 'send.cpp'; then $(CYGPATH_W) 'send.cpp'; else $(CYGPATH_W) '$(srcdir)/send.cpp'; fi`

.cpp.o:
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ $<
	$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXXCOMPILE) -c -o $@ $<

.cpp.obj:
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ `$(CYGPATH_W) '$<'`
	$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXXCOMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

.cpp.lo:
	$(LTCXXCOMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ $<
	$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Plo
#	source='$<' object='$@' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LTCXXCOMPILE) -c -o $@ $<

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs

distclean-libtool:
	-rm -f libtool config.lt

ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
	list='$(SOURCES) $(HEADERS) $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	mkid -fID $$unique
tags: TAGS

TAGS:  $(HEADERS) $(SOURCES) config.h.in $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	set x; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS) config.h.in $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: CTAGS
CTAGS:  $(HEADERS) $(SOURCES) config.h.in $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	list='$(SOURCES) $(HEADERS) config.h.in $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags

distdir: $(DISTFILES)
	$(am__remove_distdir)
	test -d "$(distdir)" || mkdir "$(distdir)"
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
	-test -n "$(am__skip_mode_fix)" \
	|| find "$(distdir)" -type d ! -perm -755 \
		-exec chmod u+rwx,go+rx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r "$(distdir)"
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | bzip2 -9 -c >$(distdir).tar.bz2
	$(am__remove_distdir)

dist-lzma: distdir
	tardir=$(distdir) && $(am__tar) | lzma -9 -c >$(distdir).tar.lzma
	$(am__remove_distdir)

dist-xz: distdir
	tardir=$(distdir) && $(am__tar) | xz -c >$(distdir).tar.xz
	$(am__remove_distdir)

dist-tarZ: distdir
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__remove_distdir)

dist-shar: distdir
	shar $(distdir) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).shar.gz
	$(am__remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__remove_distdir)

dist dist-all: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bzip2 -dc $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.lzma*) \
	  lzma -dc $(distdir).tar.lzma | $(am__untar) ;;\
	*.tar.xz*) \
	  xz -dc $(distdir).tar.xz | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	esac
	chmod -R a-w $(distdir); chmod a+w $(distdir)
	mkdir $(distdir)/_build
	mkdir $(distdir)/_inst
	chmod a-w $(distdir)
	test -d $(distdir)/_build || exit 0; \
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && am__cwd=`pwd` \
	  && $(am__cd) $(distdir)/_build \
	  && ../configure --srcdir=.. --prefix="$$dc_install_base" \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck \
	  && cd "$$am__cwd" \
	  || exit 1
	$(am__remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e 1h -e 1s/./=/g -e 1p -e 1x -e '$$p' -e '$$x'
distuninstallcheck:
	@$(am__cd) '$(distuninstallcheck_dir)' \
	&& test `$(distuninstallcheck_listfiles) | wc -l` -le 1 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: $(BUILT_SOURCES)
	$(MAKE) $(AM_MAKEFLAGS) check-am
all-am: Makefile $(LTLIBRARIES) $(PROGRAMS) config.h
install-binPROGRAMS: install-libLTLIBRARIES

installdirs:
	for dir in "$(DESTDIR)$(libdir)" "$(DESTDIR)$(bindir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: $(BUILT_SOURCES)
	$(MAKE) $(AM_MAKEFLAGS) install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	  install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	  `test -z '$(STRIP)' || \
	    echo "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'"` install
mostlyclean-generic:

clean-generic:
	-test -z "$(CLEANFILES)" || rm -f $(CLEANFILES)

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
	-test -z "$(BUILT_SOURCES)" || rm -f $(BUILT_SOURCES)
clean: clean-am

clean-am: clean-binPROGRAMS clean-generic clean-libLTLIBRARIES \
	clean-libtool clean-local mostlyclean-am

distclean: distclean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-hdr distclean-libtool distclean-tags

dvi: dvi-am

dvi-am:

html: html-am

html-am:

info: info-am

info-am:

install-data-am:

install-dvi: install-dvi-am

install-dvi-am:

install-exec-am: install-binPROGRAMS install-libLTLIBRARIES

install-html: install-html-am

install-html-am:

install-info: install-info-am

install-info-am:

install-man:

install-pdf: install-pdf-am

install-pdf-am:

install-ps: install-ps-am

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic \
	mostlyclean-libtool

pdf: pdf-am

pdf-am:

ps: ps-am

ps-am:

uninstall-am: uninstall-binPROGRAMS uninstall-libLTLIBRARIES

.MAKE: all check install install-am install-strip

.PHONY: CTAGS GTAGS all all-am am--refresh check check-am clean \
	clean-binPROGRAMS clean-generic clean-libLTLIBRARIES \
	clean-libtool clean-local ctags dist dist-all dist-bzip2 \
	dist-gzip dist-lzma dist-shar dist-tarZ dist-xz dist-zip \
	distcheck distclean distclean-compile distclean-generic \
	distclean-hdr distclean-libtool distclean-tags distcleancheck \
	distdir distuninstallcheck dvi dvi-am html html-am info \
	info-am install install-am install-binPROGRAMS install-data \
	install-data-am install-dvi install-dvi-am install-exec \
	install-exec-am install-html install-html-am install-info \
	install-info-am install-libLTLIBRARIES install-man install-pdf \
	install-pdf-am install-ps install-ps-am install-strip \
	installcheck installcheck-am installdirs maintainer-clean \
	maintainer-clean-generic mostlyclean mostlyclean-compile \
	mostlyclean-generic mostlyclean-libtool pdf pdf-am ps ps-am \
	tags uninstall uninstall-am uninstall-binPROGRAMS \
	uninstall-libLTLIBRARIES


miniDHT_proto.pb.h: miniDHT_proto.proto
	protoc miniDHT_proto.proto --cpp_out=.
miniDHT_proto.pb.cc: miniDHT_proto.proto
	protoc miniDHT_proto.proto --cpp_out=.

BitSmear.app: Info.plist BitSmear miniDHT_server miniDHT_send miniDHT_recv
	-mkdir BitSmear.app
	-mkdir BitSmear.app/Contents
	-mkdir BitSmear.app/Contents/MacOS
	-mkdir BitSmear.app/Contents/Frameworks
	-mkdir BitSmear.app/Contents/Resources
	-mkdir BitSmear.app/Contents/Resources/English.lproj
	cp -f Info.plist BitSmear.app/Contents
	cp -f Knob\ Download.png BitSmear.app/Contents/Resources
	cp -f Knob\ Upload.png BitSmear.app/Contents/Resources
	cp -f Knob\ Record\ On.png BitSmear.app/Contents/Resources
	cp -f Knob\ Record\ Off.png BitSmear.app/Contents/Resources
	cp -f Knob\ Info.png BitSmear.app/Contents/Resources
	cp -f Knob\ Cancel.png BitSmear.app/Contents/Resources
	cp -f Knob\ Grey.png BitSmear.app/Contents/Resources
	echo -n 'APPL????' > BitSmear.app/Contents/PkgInfo
	cp -f BitSmear BitSmear.app/Contents/MacOS/BitSmear
	cp -f miniDHT_server BitSmear.app/Contents/MacOS/
	cp -f miniDHT_send BitSmear.app/Contents/MacOS/
	cp -f miniDHT_recv BitSmear.app/Contents/MacOS/
	cp -af /opt/local/lib/libboost_thread-mt.dylib BitSmear.app/Contents/Frameworks/
	cp -af /opt/local/lib/libboost_system-mt.dylib BitSmear.app/Contents/Frameworks/
	cp -af /opt/local/lib/libboost_program_options-mt.dylib BitSmear.app/Contents/Frameworks/
	cp -af /opt/local/lib/libboost_date_time-mt.dylib BitSmear.app/Contents/Frameworks/
	cp -af /opt/local/lib/libboost_filesystem-mt.dylib BitSmear.app/Contents/Frameworks/
	cp -af /opt/local/lib/libprotobuf.7.dylib BitSmear.app/Contents/Frameworks/
	cp -af /opt/local/lib/libSDL-1.2.0.dylib BitSmear.app/Contents/Frameworks/
	cp -af /opt/local/lib/libiconv.2.dylib BitSmear.app/Contents/Frameworks/
	cp -af /opt/local/lib/libexpat.1.5.2.dylib BitSmear.app/Contents/Frameworks/
	cp -af /opt/local/lib/libpng14.14.dylib BitSmear.app/Contents/Frameworks/
	cp -af /opt/local/lib/libjpeg.8.dylib BitSmear.app/Contents/Frameworks/
	cp -af /opt/local/lib/libtiff.3.dylib BitSmear.app/Contents/Frameworks/
	cp -af /opt/local/lib/libwx*2.9.2.0.0.dylib BitSmear.app/Contents/Frameworks
	./embed_macosxlib.sh BitSmear
#	cp -af /opt/local/lib/libboost_serialization-mt.dylib BitSmear.app/Contents/Frameworks/

clean-local:
	-rm -rf BitSmear.app

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
